---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-helm
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helm
  namespace: ch-helm
spec:
  type: helmrepo
  pathname: https://ianzhang366.github.io/guestbook-chart/
