---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ns
  namespace: ch-ns
spec:
  type: Namespace
  pathname: ch-ns
  sourceNamespaces:
    - default
