apiVersion: v1
kind: Namespace
metadata:
  name: helm-local
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: helm-local
spec:
  clusterSelector: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helm-ch
  namespace: helm-local
  labels:
    app: local-helm-gb
spec:
  type: HelmRepo
  pathname: https://ianzhang366.github.io/guestbook-chart/
  insecureSkipVerify: true
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: local-sub-test
  namespace: helm-local
  labels:
    app: local-helm-gb

spec:
  channel: helm-local/helm-ch
  name: gbapp
  packageFilter:
    version: "0.1.0"
  placement:
    local: true
  packageOverrides:
  - packageName: nginx-ingress
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 1
