# this only test the channel namespace promotion logic. TODO: need to find a way
# to test the object store got the promoted object
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: ch-obj
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: backend-test
  namespace: ch-obj
spec:
  type: ObjectBucket
  pathname: http://ec2-34-227-89-198.compute-1.amazonaws.com:9000/backend-test
  sourceNamespaces:
    - default
  secretRef:
    name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dev
  namespace: ch-obj
data:
  AccessKeyID: YWRtaW4= #<base64 encode username>
  SecretAccessKey: cGFzc3dvcmRhZG1pbg== #<base64 encode password>
